load('//day_base:day_cc_solution.bzl', 'day_cc_solution')

cc_library(
    name = "passport",
    srcs = ["passport.c"],
    hdrs = ["passport.h"],
)

day_cc_solution(
    year = '2020',
    day = 'day4',
    deps = [":passport"],
)
