load('//day_base:day_cc_solution.bzl', 'day_cc_solution')

day_cc_solution(
    year = '2020',
    day = 'day14',
    examples = ['example', 'example2'],
    deps = ['//day_base/struct:array', '//day_base/struct:hashmap'],
)
